= Installation overview

The OpenShift Container Platform installation program offers you flexibility. You can use the installation program to deploy a cluster on infrastructure that the installation program provisions and the cluster maintains or deploy a cluster on infrastructure that you prepare and maintain.

These two basic types of OpenShift Container Platform clusters are frequently called
installer-provisioned infrastructure clusters and user-provisioned
infrastructure clusters.

Both types of clusters have the following characteristics:

* Highly available infrastructure with no single points of failure is available
by default
* Administrators maintain control over what updates are applied and when

You use the same installation program to deploy both types of clusters. The main assets generated by the installation program are the Ignition config files for the bootstrap, master, and worker machines. With these three configurations and correctly configured infrastructure, you can start an OpenShift Container Platform cluster.

The OpenShift Container Platform installation program uses a set of targets and dependencies to manage cluster installation. The installation program has a set of targets that it must achieve, and each target has a set of dependencies. Because each target is only concerned with its own dependencies, the installation program can act to achieve multiple targets in parallel. The ultimate target is a running cluster. By meeting dependencies instead of running commands, the installation program is able to recognize and use existing components instead of running the commands to create them again.

== Installation process

When you install an OpenShift Container Platform cluster, you download the
installation program from the appropriate
link:https://cloud.redhat.com/openshift/install[Infrastructure Provider]
page on the {cloud-redhat-com} site. This site manages:

* REST API for accounts
* Registry tokens, which are the pull secrets that you use to obtain the required
components
* Cluster registration, which associates the cluster identity to your Red Hat
account to facilitate the gathering of usage metrics

In OpenShift Container Platform, the installation program is a Go binary file that performs a
series of file transformations on a set of assets. The way you interact with the
installation program differs depending on your installation type.

* For clusters with installer-provisioned infrastructure, you delegate the
infrastructure bootstrapping and provisioning to the installation program
instead of doing it yourself. The installation program creates all of the
networking, machines, and operating systems that are required to support the
cluster.

* If you provision and manage the infrastructure for your cluster, you must
provide all of the cluster infrastructure and resources, including the
bootstrap machine, networking, load balancing, storage, and individual cluster
machines. You cannot use the advanced machine management and scaling capabilities
that an installer-provisioned infrastructure cluster offers.

You use three sets of files during installation: an installation configuration
file that is named `install-config.yaml`, Kubernetes manifests, and Ignition
config files for your machine types.

[IMPORTANT]
====
It is possible to modify Kubernetes and the Ignition config files that control
the underlying RHCOS operating system during installation. However,
no validation is available to confirm the suitability of any modifications that
you make to these objects. If you modify these objects, you might render
your cluster non-functional. Because of this risk, modifying Kubernetes and
Ignition config files is not supported unless you are following documented procedures
or are instructed to do so by Red Hat support.
====

The installation configuration file is transformed into Kubernetes manifests, and
then the manifests are wrapped into Ignition config files. The installation program uses
these Ignition config files to create the cluster.

The installation configuration files are all pruned when you run the installation program,
so be sure to back up all configuration files that you want to use again.

[IMPORTANT]
====
You cannot modify the parameters that you set during installation, but you can
modify many cluster attributes after installation.
====

=== Installation process details

Because each machine in the cluster requires information about the cluster when
it is provisioned, OpenShift Container Platform uses a temporary _bootstrap_ machine during
initial configuration to provide the required information to the permanent
control plane. It boots by using an Ignition config file that describes how to
create the cluster. The bootstrap machine creates the master machines that
make up the control plane. The control plane machines then create the compute machines, which are also known as worker machines.

After the cluster machines initialize, the bootstrap machine is destroyed.
All clusters use the bootstrap process to initialize the
cluster, but if you provision the infrastructure for your cluster, you must
complete many of the steps manually.

[IMPORTANT]
====
The Ignition config files that the installation program generates contain
certificates that expire after 24 hours. You must complete your cluster
installation and keep the cluster running for 24 hours in a non-degraded state
to ensure that the first certificate rotation has finished.
====

Bootstrapping a cluster involves the following steps:

. The bootstrap machine boots and starts hosting the remote resources required
for the master machines to boot. (Requires manual intervention if you provision
  the infrastructure)
. The master machines fetch the remote resources from the bootstrap machine
and finish booting. (Requires manual intervention if you provision the
  infrastructure)
. The master machines use the bootstrap machine to form an etcd cluster.
. The bootstrap machine starts a temporary Kubernetes control plane using the
new etcd cluster.
. The temporary control plane schedules the production control plane to the
master machines.
. The temporary control plane shuts down and passes control to the production
control plane.
. The bootstrap machine injects OpenShift Container Platform components into the production
control plane.
. The installation program shuts down the bootstrap machine.
(Requires manual intervention if you provision the infrastructure)
. The control plane sets up the worker nodes.
. The control plane installs additional services in the form of a set
of Operators.

The result of this bootstrapping process is a fully running OpenShift Container Platform
cluster. The cluster then downloads and configures remaining components
needed for the day-to-day operation, including the creation of worker machines
in supported environments.
