= Linux Namespaces

kernel namespaces are the fundamental building block of containers on Linux.

== Background

Linux Namespaces provide the fundamentals of container isolation. A namespace makes it appear
to the processes within the namespace that they have their own instance of global resources.
Namespaces provide the abstraction that gives the impression you are running on your own oper-
ating system when you are inside a container.

== Description

Namespaces create the sandbox that isolates a process from other processes running outside of the sandbox, 
We will deep dive into the Linux internals that enable containers to work. 
Containers will be demystified so developers and admins will have a better grasp at what their favorite container engine is doing at runtime.

== What you will learn

- How a container is made
- Linux Namespaces and how they impact running processes
- What is stored in a OCI image file
- How the container filesystem is constructed
- How the container network stack is constructed


== PODMAN

New Linux Namespaces are typically spawned by using either the clone or unshare system calls. 
These exist as C functions but wrappers exist in many other languages.  We will use the *unshare* command.

```
unshare --help

Usage:
 unshare [options] [<program> [<argument>...]]

Run a program with some namespaces unshared from the parent.

Options:
 -m, --mount[=<file>]      unshare mounts namespace
 -u, --uts[=<file>]        unshare UTS namespace (hostname etc)
 -i, --ipc[=<file>]        unshare System V IPC namespace
 -n, --net[=<file>]        unshare network namespace
 -p, --pid[=<file>]        unshare pid namespace
 -U, --user[=<file>]       unshare user namespace
 -C, --cgroup[=<file>]     unshare cgroup namespace
 -f, --fork                fork before launching <program>
     --kill-child[=<signame>]  when dying, kill the forked child (implies --fork); defaults to SIGKILL
     --mount-proc[=<dir>]  mount proc filesystem first (implies --mount)
 -r, --map-root-user       map current user to root (implies --user)
     --propagation slave|shared|private|unchanged
                           modify mount propagation in mount namespace
 -s, --setgroups allow|deny  control the setgroups syscall in user namespaces

 -h, --help                display this help
 -V, --version             display version

For more details see unshare(1).
```

