== How Containers are Secured on Red Hat Enterprise Linux CoreOS

Containers enable you to simplify multi-tenancy deployments by deploying
multiple applications on a single host, using the kernel and the container runtime
to spin up each container.

You must have an operating system (OS) that can secure the host kernel and
secure containers from each other. In Linux, containers are just a special type
of process, so securing containers is the same as securing any running process.
Containers should run as a *non-root user*. *Dropping the privilege level or
creating containers with the least amount of privileges possible is recommended*.

Because OpenShift runs on RHCOS and RHEL, the following concepts apply by default to any deployed
cluster and are at the core of what make containers secure on the platform.

- _Linux namespaces_ enable creating an abstraction of a particular global system
resource to make it appear as a separate instance to processes within a
namespace. Consequently, several containers can use the same resource
simultaneously without creating a conflict.

- _SELinux_ provides an additional layer of security to keep containers isolated
from each other and from the host. SELinux allows administrators to enforce
mandatory access controls (MAC) for every user, application, process, and file.

Container processes always get the _container_t_ context type and the files and directories the containers need to access on the host system get the container_file_t context type. 

MCS is a SELinux feature that assigns two categories between c0 and c1023 to containers, with two categories the limit is about 500,000 containers per host. OpenShift allocates the two random categories at the project level and by default, all pods and containers in a project get the same category pair. This is useful when multiple containers in the project need to access the same shared volume.

- _CGroups_ (control groups) limit, account for, and isolate the resource usage
(CPU, memory, disk I/O, network, etc.) of a collection of processes. CGroups are
used to ensure that containers on the same host are not impacted by each other.

- _Secure computing mode (seccomp)_ profiles can be associated with a container to
restrict available system calls.

- Deploying containers using _RHCOS_ reduces the attack surface by minimizing the host environment and tuning it for containers.

== Multi-tenancy: Virtualization Versus Containers

Traditional virtualization also enables multi-tenancy, but in a very different
way from containers. Virtualization relies on a hypervisor spinning up guest
virtual machines (VMs), each of which has its own operating system (OS), as well
as the running application and its dependencies.

With VMs, the hypervisor isolates the guests from each other and from the host
kernel. Fewer individuals and processes have access to the hypervisor, reducing
the attack surface on the physical server. That said, security must still be
monitored: one guest VM may be able to use hypervisor bugs to gain access to
another VM or the host kernel. And, when the OS needs patching, it must be
patched on all guest VMs using that OS.

Containers can be run inside guest VMs, and there may be use cases where this is
desirable. For example, you may be deploying a traditional application in a
container, perhaps in order to lift-and-shift an application to the cloud.
However, container multi-tenancy on a single host provides a more lightweight,
flexible, and easier-to-scale deployment solution. This deployment model is
particularly appropriate for cloud-native applications.

