= Introduction to OpenShift Container Platform

OpenShift Container Platform is a platform for developing and running containerized
applications. It is designed to allow applications and the data centers
that support them to expand from just a few machines and applications to
thousands of machines that serve millions of clients.

With its foundation in Kubernetes, OpenShift Container Platform incorporates the same
technology that serves as the engine for massive telecommunications, streaming
video, gaming, banking, and other applications. Its implementation in open
Red Hat technologies lets you extend your containerized applications beyond a
single cloud to on-premise and multi-cloud environments.

= About Kubernetes

Although container images and the containers that run from them are the
primary building blocks for modern application development, to run them at scale
requires a reliable and flexible distribution system. Kubernetes is the
defacto standard for orchestrating containers.

Kubernetes is an open source container orchestration engine for automating
deployment, scaling, and management of containerized applications. The general
concept of Kubernetes is fairly simple:

* Start with one or more worker nodes to run the container workloads.
* Manage the deployment of those workloads from one or more master nodes.
* Wrap containers in a deployment unit called a Pod. Using Pods provides extra
metadata with the container and offers the ability to group several containers
in a single deployment entity.
* Create special kinds of assets. For example, services are represented by a
set of Pods and a policy that defines how they are accessed. This policy
allows containers to connect to the services that they need even if they do not
have the specific IP addresses for the services. Replication controllers are
another special asset that indicates how many Pod Replicas are required to run
at a time. You can use this capability to automatically scale your application
to adapt to its current demand.

In only a few years, Kubernetes has seen massive cloud and on-premise adoption.
The open source development model allows many people to extend Kubernetes
by implementing different technologies for components such as networking,
storage, and authentication.

= OpenShift Container Platform overview

OpenShift Container Platform provides enterprise-ready enhancements to Kubernetes, including the following enhancements:

* Hybrid cloud deployments. You can deploy OpenShift Container Platform clusters to variety of public cloud platforms or in your data center.

* Integrated Red Hat technology. Major components in OpenShift Container Platform come from Red Hat Enterprise Linux and related Red Hat technologies. OpenShift Container Platform benefits from the intense testing and certification initiatives for Red Hat’s enterprise quality software.
* Open source development model. Development is completed in the open, and the source code is available from public software repositories. This open collaboration fosters rapid innovation and development.

Although Kubernetes excels at managing your applications, it does not specify
or manage platform-level requirements or deployment processes. Powerful and
flexible platform management tools and processes are important benefits that
OpenShift Container Platform offers. The following sections describe some
unique features and benefits of OpenShift Container Platform.

== Custom operating system

OpenShift Container Platform uses RHCOS, a container-oriented operating
system that combines some of the best features and functions of the CoreOS and
Red Hat Atomic Host operating systems. RHCOS is specifically designed for
running containerized applications from OpenShift Container Platform and works with new tools
to provide fast installation, Operator-based management, and simplified upgrades.

== Simplified installation and update process

With OpenShift Container Platform, if you have an account with the right
permissions, you can deploy a production cluster in supported clouds by running
a single command and providing a few values. You can also customize your cloud
installation or install your cluster in your data center if you use a supported
platform.

For clusters that use RHCOS for all machines, updating, or
upgrading, OpenShift Container Platform is a simple, highly-automated process. Because
OpenShift Container Platform completely controls the systems and services that run on each
machine, including the operating system itself, from a central control plane,
upgrades are designed to become automatic events. If your cluster contains
RHEL worker machines, the control plane benefits from the streamlined update
process, but you must perform more tasks to upgrade the RHEL machines.

== Other key features

Operators are both the fundamental unit of the OpenShift Container Platform
code base and a convenient way to deploy applications and software components
for your applications to use. In OpenShift Container Platform, Operators serve as the platform foundation and remove the need for manual upgrades of operating systems and control plane applications. OpenShift Container Platform Operators such as the
Cluster Version Operator and Machine Config Operator allow simplified,
cluster-wide management of those critical components.

Operator Lifecycle Manager (OLM) and the OperatorHub provide facilities for
storing and distributing Operators to people developing and deploying applications.

The Red Hat Quay Container Registry is a Quay.io container registry that serves
most of the container images and Operators to OpenShift Container Platform clusters.
Quay.io is a public registry version of Red Hat Quay that stores millions of images
and tags.

Other enhancements to Kubernetes in OpenShift Container Platform include improvements in
software defined networking (SDN), authentication, log aggregation, monitoring,
and routing. OpenShift Container Platform also offers a comprehensive web console and the
custom OpenShift CLI (`oc`) interface.


////
OpenShift Container Platform includes the following infrastructure components:

* OpenShift API server
* Kubernetes API server
* Kubernetes controller manager
* Kubernetes nodes/kubelet
* CRI-O
* RHCOS
* Infrastructure Operators
* Networking (SDN/Router/DNS)
* Storage
* Monitoring
* Telemetry
* Security
* Authorization/Authentication/Oauth
* Logging

It also offers the following user interfaces:
* Web Console
* OpenShift CLI (`oc`)
* Rest API
////

