= About the OpenShift update service

The OpenShift update service is the hosted service that provides over-the-air
updates to both OpenShift and RHCOS. It provides a graph,
or diagram that contain _vertices_ and the _edges_ that connect them, of
component Operators. The edges in the graph show which versions you can safely
update to, and the vertices are update payloads that specify the intended state
of the managed cluster components.

The Cluster Version Operator (CVO) in your cluster checks with the
OpenShift update service to see the valid updates and update paths based
on current component versions and information in the graph. When you request an
update, the OpenShift CVO uses the release image for that update to
upgrade your cluster. The release artifacts are hosted in Quay as container
images.

////
By accepting automatic updates, you can automatically
keep your cluster up to date with the most recent compatible components.
////

To allow the OpenShift update service to provide only compatible updates,
a release verification pipeline exists to drive automation. Each release
artifact is verified for compatibility with supported cloud platforms and system
architectures as well as other component packages. After the pipeline confirms
the suitability of a release, the OpenShift update service notifies you
that it is available.

[IMPORTANT]
====
Because the update service displays all valid updates, you must not force an update to a version that the update service does not display.
====

////
The interaction between the registry and the OpenShift update service is different during
bootstrap and continuous update modes. When you bootstrap the initial
infrastructure, the Cluster Version Operator finds
the fully qualified image name for the shortname of the images that it needs to
apply to the server during installation. It looks at the imagestream that it needs
to apply and renders it to disk. It calls bootkube and waits for a temporary minimal control
plane to come up and load the Cluster Version Operator.
////

During continuous update mode, two controllers run. One continuously updates
the payload manifests, applies them to the cluster, and outputs the status of
the controlled rollout of the Operators, whether they are available, upgrading,
or failed. The second controller polls the OpenShift update service to
determine if updates are available.

[IMPORTANT]
====
Reverting your cluster to a previous version, or a rollback, is not supported.
Only upgrading to a newer version is supported.
====

During the upgrade process, the Machine Config Operator (MCO) applies the new configuration to your cluster machines. It cordons the number of nodes that is specified by the `maxUnavailable` field on the machine configuration pool and marks them as unavailable. By default, this value is set to `1`. It then applies the new configuration and reboots the machine. If you use Red Hat Enterprise Linux (RHEL) machines as workers, the MCO does not update the kubelet on these machines because you must update the OpenShift API on them first. Because the specification for the new version is applied to the old kubelet, the RHEL machine cannot return to the `Ready` state. You cannot complete the update until the machines are available. However, the maximum number of nodes that are unavailable is set to ensure that normal cluster operations are likely to continue with that number of machines out of service.

= OpenShift upgrade channels and releases

In OpenShift 4.1, Red Hat introduced the concept of channels for
recommending the appropriate release versions for cluster upgrade. By controlling
the pace of upgrades, these upgrade channels allow you to choose an upgrade
strategy. Upgrade channels are tied to a minor version of
OpenShift. For instance, OpenShift 4.x
upgrade channels will never include an upgrade to a 4.y release. This strategy ensures that
administrators explicitly decide to upgrade to the next minor version of
OpenShift. Upgrade channels control only release selection and do not impact the version of the cluster that you install; the `openshift-install`
binary file for a specific version of OpenShift always installs that version.

OpenShift 4.x offers the following upgrade channels:

* `candidate-4.x`
* `fast-4.x`
* `stable-4.x`

== candidate-4.x channel

The `candidate-4.x` channel contains candidate builds for a z-stream
(4.x.z) release.
Release candidates contain all the features of the product but are not supported. Use release candidate versions to test feature acceptance and assist in qualifying the next version
of OpenShift.
A release candidate is any build that is available in the candidate channel, including ones that do not contain `-rc` in their names.
After a version is available in the candidate channel, it goes through more quality checks. If
it meets the quality standard, it is promoted to the `fast-4.x` or `stable-4.x` channels.
Because of this strategy, if a specific release is available in both the `candidate-4.x` channel and in the `fast-4.x`
or `stable-4.x` channels, it is a Red Hat supported version.
The `candidate-4.x` channel can include release versions from which there are no recommended updates in any channel.

You can use the `candidate-4.x` channel to upgrade from a previous minor version of
OpenShift.

[NOTE]
====
Release candidates differ from the nightly builds found on the https://www.openshift.com/try site. Nightly
builds are available for early access to features, but updating to or from nightly
builds is neither recommended nor supported. Nightly builds are not available in
any upgrade channel.
====

== fast-4.x channel

The `fast-4.x` channel is updated with new 4.x
versions as soon as Red Hat declares the given version as a general availability
release. As such, these releases are fully supported, are production quality, and have
performed well while available as a release candidate in the `candidate-4.x`
channel from where they were promoted. Some time after a release appears in the
`fast-4.x` channel, it is added to the `stable-4.x` channel. Releases
never appear in the `stable-4.x` channel before they appear in the `fast-4.x` channel.

You can use the `fast-4.x` channel to upgrade from a previous minor version of
OpenShift.

== stable-4.x channel

While the `fast-4.x` channel contains releases as soon
as their errata are published, releases are added to the `stable-4.x` channel
after a delay of several hours to a day. During this delay, data is collected from Red Hat SRE teams, Red Hat support services, and pre-production and production environments that participate in connected customer program about the stability of the release.

You can use the `stable-4.x` channel to upgrade from a previous minor version of
OpenShift.

== Upgrade version paths

OpenShift maintains an upgrade recommendation service that understands the
version of OpenShift you have installed as well as the path to take within
the channel you choose to get you to the next release. You can imagine seeing the
following in the `fast-4.x` channel:

* 4.x.0
* 4.x.1
* 4.x.3
* 4.x.4

The service recommends only upgrades that have been tested and have no serious issues.
If your cluster is on 4.x.1 and OpenShift suggests
4.x.4, then it is safe for you to update from .4.x.1 to .4.x.4. Do not rely on consecutive patch numbers. In this example, 4.x.2 is not, and never was, available in the channel. The update service will not suggest updating to a version of OpenShift that contains known vulnerabilities.

Update stability depends on your channel. The presence of an update recommendation in
the `candidate-4.x` channel does not imply that the update is supported.
It means that no serious issues have been found with the update yet, but there might
not be significant traffic through the update to suggest stability. The presence of
an update recommendation in the `fast-4.x` or `stable-4.x`
channels is a declaration that the update is fully supported while it is in the
channel. While releases will never be removed from a channel, update recommendations
that exhibit serious issues will be removed from all channels. Updates initiated
after the update recommendation has been removed might not be supported.

Red Hat will eventually provide supported update paths from any supported release in the `fast-4.x`
or `stable-4.x` channels to the latest release in 4.x.z,
although there can be delays while safe paths away from troubled releases are
constructed and verified.

== Fast and stable channel use and strategies

The `fast-4.x` and `stable-4.x` channels present a choice between receiving
general availability releases as soon as they are available or allowing Red Hat to
control the rollout of those updates. If issues are detected during rollout or at a
later time, upgrades to that version might be blocked in both the `fast-4.x` and
`stable-4.x` channels, and a new version might be introduced that becomes the new
preferred upgrade target.

Customers can improve this process by configuring pre-production systems on the
`fast-4.x` channel, configuring production systems on the `stable-4.x` channel,
and participating in Red Hat’s connected customer program. Red
Hat uses this program to observe the impact of updates on your specific hardware and software
configurations. Future releases might improve or alter the pace at which updates move
from the `fast-4.x` to the `stable-4.x` channel.

== Restricted network clusters

If you manage the container images for your OpenShift clusters yourself, you must consult the Red Hat errata that is associated with product releases and note any comments that impact upgrades.
During upgrade, the user interface might warn you about switching between these versions,
so you must ensure that you selected an appropriate version before you bypass those warnings.

== Switching between channels

Your cluster is still supported if you change from the `stable-4.x` channel to
the `fast-4.x` channel. Although you can switch to the
`candidate-4.x` channel at any time, some releases in that channel might be unsupported release candidates.
You can switch from the `candidate-4.x` channel to the `fast-4.x` channel
if your current release is a general availability release. You can always
switch from the `fast-4.x` channel to the `stable-4.x` channel, although if the current release was recently promoted to
`fast-4.x` there can
be a delay of up to a day for the release to be promoted to
`stable-4.x`. If you change to a channel that does not include your
current release, an alert displays and no updates can be recommended, but you can
safely change back to your original channel at any point.
