== About This WorkShop

This workshop provides a high-level walkthrough of the OpenShift security measures, including solutions for the host layer, the
container and orchestration layer, and the build and application layer. 


== Introduction

Securing containers is a lot like securing any running process. You need to think about security
throughout the layers of the solution stack before you deploy and run your container. You also need
to think about security throughout the application and container life cycle.

This workshop will cover the following modules:

- Container Host & Multi Tenancy.
* Red Hat Enterprise Linux CoreOS
* Linux NameSpaces
* Linux Capabilities
* Building your own container from Scratch
- Trusted Sources.
- Secure Access to Container Images.
- Security and the Build Process.
- Controling what can be deployed within a cluster.
- Securing the container Platform.
- Network Security for Apps on Openshift.
- Secure the Data.
- API Management and SSO.
- Introduction to Gitops.

== Security in OpenShift

This workshop describes the key elements of security for each layer of the
container solution stack, while also showing how OpenShift can be used to
to create, deploy, and manage containers at scale, with security in mind at
every stage and every layer.